// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodes.proto

package trie

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Bitmap is an array of bits.
//
// Since 0.5.10
type Bitmap struct {
	// Words contains bitmap
	//
	// Since 0.5.10
	Words []uint64 `protobuf:"varint,20,rep,packed,name=Words,proto3" json:"Words,omitempty"`
	// RankIndex speeds up rank() by pre-calcuate it
	//
	// Since 0.5.10
	RankIndex []int32 `protobuf:"varint,30,rep,packed,name=RankIndex,proto3" json:"RankIndex,omitempty"`
	// SelectIndex speeds up select() by pre-calcuate it
	//
	// Since 0.5.10
	SelectIndex          []int32  `protobuf:"varint,40,rep,packed,name=SelectIndex,proto3" json:"SelectIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bitmap) Reset()         { *m = Bitmap{} }
func (m *Bitmap) String() string { return proto.CompactTextString(m) }
func (*Bitmap) ProtoMessage()    {}
func (*Bitmap) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_a3bde4bab6df15cb, []int{0}
}
func (m *Bitmap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bitmap.Unmarshal(m, b)
}
func (m *Bitmap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bitmap.Marshal(b, m, deterministic)
}
func (dst *Bitmap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bitmap.Merge(dst, src)
}
func (m *Bitmap) XXX_Size() int {
	return xxx_messageInfo_Bitmap.Size(m)
}
func (m *Bitmap) XXX_DiscardUnknown() {
	xxx_messageInfo_Bitmap.DiscardUnknown(m)
}

var xxx_messageInfo_Bitmap proto.InternalMessageInfo

func (m *Bitmap) GetWords() []uint64 {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *Bitmap) GetRankIndex() []int32 {
	if m != nil {
		return m.RankIndex
	}
	return nil
}

func (m *Bitmap) GetSelectIndex() []int32 {
	if m != nil {
		return m.SelectIndex
	}
	return nil
}

// InnerNodes is array of all inner nodes in slim trie.
// It is NOT a public type and do not rely on it.
// Since protobuf just makes all message public.
//
// Since 0.5.10
type InnerNodes struct {
	// Flags provides options
	//
	// Since 0.5.10
	Flags uint32 `protobuf:"varint,10,opt,name=Flags,proto3" json:"Flags,omitempty"`
	// Index is a bitmap in which a "1" indicates the i-th element exists.
	//
	// Since 0.5.10
	Index *Bitmap `protobuf:"bytes,20,opt,name=Index,proto3" json:"Index,omitempty"`
	// Elts is a array of var-length node label bitmaps.
	// The size of an element bitmap is aligned to 4.
	//
	// Since 0.5.10
	Elts *Bitmap `protobuf:"bytes,30,opt,name=Elts,proto3" json:"Elts,omitempty"`
	// Starts is a bitmap in which the i-th "1" is where the i-th element
	// starts.
	// To get the start position of i-th element:
	//     s := Starts.Select(i)
	//
	// To get the end position of i-th element:
	//     e := Starts.Select(i+1)
	//
	// Since 0.5.10
	Starts               *Bitmap  `protobuf:"bytes,40,opt,name=Starts,proto3" json:"Starts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerNodes) Reset()         { *m = InnerNodes{} }
func (m *InnerNodes) String() string { return proto.CompactTextString(m) }
func (*InnerNodes) ProtoMessage()    {}
func (*InnerNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_a3bde4bab6df15cb, []int{1}
}
func (m *InnerNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNodes.Unmarshal(m, b)
}
func (m *InnerNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNodes.Marshal(b, m, deterministic)
}
func (dst *InnerNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNodes.Merge(dst, src)
}
func (m *InnerNodes) XXX_Size() int {
	return xxx_messageInfo_InnerNodes.Size(m)
}
func (m *InnerNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNodes.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNodes proto.InternalMessageInfo

func (m *InnerNodes) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *InnerNodes) GetIndex() *Bitmap {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *InnerNodes) GetElts() *Bitmap {
	if m != nil {
		return m.Elts
	}
	return nil
}

func (m *InnerNodes) GetStarts() *Bitmap {
	if m != nil {
		return m.Starts
	}
	return nil
}

func init() {
	proto.RegisterType((*Bitmap)(nil), "Bitmap")
	proto.RegisterType((*InnerNodes)(nil), "InnerNodes")
}

func init() { proto.RegisterFile("nodes.proto", fileDescriptor_nodes_a3bde4bab6df15cb) }

var fileDescriptor_nodes_a3bde4bab6df15cb = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x29, 0x6d, 0x23, 0xbe, 0xe2, 0x12, 0x3a, 0x04, 0xd4, 0x1a, 0x3a, 0x65, 0xea, 0xa0,
	0x7f, 0x50, 0x50, 0xe8, 0xe2, 0x90, 0x0e, 0x82, 0x83, 0x10, 0x6d, 0x90, 0x62, 0x4d, 0x4a, 0x92,
	0xc1, 0xcd, 0x5f, 0x97, 0x36, 0x82, 0x76, 0xbc, 0xe7, 0xf0, 0xb8, 0xef, 0x42, 0xa2, 0x74, 0x23,
	0x6d, 0xd1, 0x1b, 0xed, 0x74, 0x7e, 0x01, 0x54, 0xb6, 0xee, 0x29, 0x7a, 0x9c, 0x42, 0x7c, 0xd2,
	0xa6, 0xb1, 0x24, 0xa5, 0x21, 0x8b, 0xb8, 0x0f, 0x78, 0x05, 0x73, 0x2e, 0xd4, 0xa3, 0x52, 0x8d,
	0x7c, 0x91, 0x8c, 0x86, 0x2c, 0xe6, 0x3f, 0x80, 0x29, 0x24, 0xb5, 0xec, 0xe4, 0xcd, 0x79, 0xcf,
	0x46, 0xff, 0x8f, 0xf2, 0x37, 0x40, 0xa5, 0x94, 0x34, 0xc7, 0xa1, 0x73, 0xe8, 0x38, 0x74, 0xe2,
	0x6e, 0x09, 0xd0, 0x80, 0x2d, 0xb8, 0x0f, 0x78, 0x0d, 0xb1, 0xbf, 0x4f, 0x69, 0xc0, 0x92, 0xed,
	0xac, 0xf0, 0x1f, 0x71, 0x4f, 0xf1, 0x12, 0xa2, 0x7d, 0xe7, 0x2c, 0xc9, 0xa6, 0x76, 0x84, 0x78,
	0x03, 0xa8, 0x76, 0xc2, 0x38, 0x4b, 0xd8, 0x54, 0x7f, 0x71, 0x89, 0xce, 0x91, 0x33, 0xad, 0xbc,
	0xa2, 0x71, 0xef, 0xee, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xe5, 0x11, 0x4d, 0xfe, 0x00, 0x00,
	0x00,
}
